name: PR CI
on:
  pull_request:
    branches: 
      - main
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Run unitary tests
        run: go test -v ./...

  test-integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Run integration tests
        run: go test -v ./... --tags=integration
        env:
          INTEGRATION_IPFS_DAEMON_URL: ${{ secrets.INTEGRATION_IPFS_DAEMON_URL }}
          INTEGRATION_IPFS_PROJECT_ID: ${{ secrets.INTEGRATION_IPFS_PROJECT_ID }}
          INTEGRATION_IPFS_PROJECT_SECRET: ${{ secrets.INTEGRATION_IPFS_PROJECT_SECRET }}
          INTEGRATION_MNEMONIC: ${{ secrets.INTEGRATION_MNEMONIC }}
          INTEGRATION_PRIVATE_KEY: ${{ secrets.INTEGRATION_PRIVATE_KEY }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Build the binary
        run: go build